version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - dbData:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: ./src/Services/StudentService/Infrastructure/EduHub.StudentService.Infrastructure.Migrator/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=EduHub-Student;Username=postgres;Password=password;
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbData:
